# Generated by Django 3.0.3 on 2020-02-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_of_production', models.IntegerField()),
                ('engine_displacement', models.IntegerField()),
                ('power', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('mileage_in_km', models.IntegerField()),
                ('intackt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GearboxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='Male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=3, max_digits=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='individualclientdetails',
            name='sex',
        ),
        migrations.AlterField(
            model_name='companyclientdetails',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
        ),
        migrations.AlterField(
            model_name='individualclientdetails',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Car')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Employee')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.House')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Position'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CarCategory'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.FuelType'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.GearboxType'),
        ),
        migrations.AddField(
            model_name='individualclientdetails',
            name='Gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Adress'),
        ),
    ]
